@startuml
!include <c4/C4_Context>

' Система
System_Boundary(monomoth_app, "Монолитное приложение управления отоплением") {
    System(monomoth, "Монолит на Go\nPostgreSQL\nСинхронная архитектура")
}

' Внешние участники
Person(user, "Пользователь", "Управляет отоплением, просматривает температуру")
Person(technician, "Специалист", "Выезд для установки и подключения датчика")
System(sensor, "Датчик температуры", "Измеряет температуру в доме")

' Связи
Rel(user, monomoth, "Управление отоплением и просмотр температуры через веб")
Rel(technician, monomoth, "Регистрация установки,\nподключение датчика")
Rel(monomoth, sensor, "Синхронный опрос температуры", "запрашивает")
Rel(sensor, monomoth, "Ответ с текущей температурой", "отвечает")

' Подпись
'Footer Диаграмма контекста (C4 Level 1) | https://c4model.com
@enduml