version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_DB: smarthome_db
      POSTGRES_USER: smarthome_user
      POSTGRES_PASSWORD: securepassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  temperature-api:
    build: .
    container_name: temperature-api
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgresql://smarthome_user:securepassword123@postgres:5432/smarthome_db
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: